# Generated by Django 4.1 on 2022-08-29 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Coder', '0003_entregable_profesor_alter_estudiantes_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('nombre',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App_Coder.estudiantes'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'camada')},
        ),
    ]
